service: backoffice-backend
frameworkVersion: "3"

provider:
  name: aws
  deploymentMethod: direct
  region: us-east-2
  runtime: nodejs18.x
  deploymentBucket:
    blockPublicAccess: true
    serverSideEncryption: AES256
  httpApi:
    name: "Backoffice"
    cors: true

plugins:
  - serverless-auto-swagger
  - serverless-prune-plugin
  - serverless-webpack
  - serverless-dotenv-plugin
  - serverless-offline

custom:
  serverless-offline:
    ignoreJWTSignature: true
  prune:
    automatic: true
    number: 3
  webpack:
    excludeRegex: \.ts|test|\.map
    includeModules:
      forceExclude:
        - aws-sdk
  autoswagger:
    typefiles: ['./src/types/api-types.d.ts']
    excludeStages: ['prd', 'uat']

package:
  excludeDevDependencies: true
  exclude:
    - ./**
  include:
    - ./src/**.ts

functions:
  login:
    name: "login"
    description: "Login with credentials"
    handler: src/functions/auth/login.handler
    events:
      - httpApi:
          method: POST
          path: /v1/auth/login
          bodyType: "LoginRequestBody"
