service: backoffice-backend
frameworkVersion: "3"

provider:
  name: aws
  deploymentMethod: direct
  region: us-east-2
  runtime: nodejs18.x
  deploymentBucket:
    blockPublicAccess: true
    serverSideEncryption: AES256
  httpApi:
    name: "Backoffice"
    cors: true
    authorizers:
      jwtAuthorizer:
        type: jwt
        name: jwtAuthorizer
        functionName: jwtAuthorizer
        issuerUrl: ${env:FIREBASE_ISSUER_URL}
        audience:
          - ${env:FIREBASE_AUDIENCE}
        resultTtlInSeconds: 300
        identitySource:
          - $request.header.Authorization

plugins:
  - serverless-auto-swagger
  - serverless-prune-plugin
  - serverless-webpack
  - serverless-dotenv-plugin
  - serverless-offline

custom:
  serverless-offline:
    ignoreJWTSignature: true
  prune:
    automatic: true
    number: 3
  webpack:
    excludeRegex: \.ts|test|\.map
    includeModules:
      forceExclude:
        - aws-sdk
  autoswagger:
    typefiles: ['./src/types/api-types.d.ts']
    excludeStages: ['prd', 'uat']

package:
  excludeDevDependencies: true
  exclude:
    - ./**
  include:
    - ./src/**.ts

functions:
  jwtAuthorizer:
    handler: src/functions/authorizer/handler.handler
    description: Authorizer for JWT integration
  login:
    name: "login"
    description: "Login with credentials"
    handler: src/functions/auth/login.handler
    events:
      - httpApi:
          method: POST
          path: /v1/auth/login
          bodyType: "LoginRequestBody"
  fiscals-create:
    name: "fiscals-create"
    description: "Create fiscal user and associates voting tables"
    handler: src/functions/fiscals/create.handler
    events:
      - httpApi:
          method: POST
          path: /v1/fiscals
          authorizer:
            name: jwtAuthorizer
            type: jwt
          bodyType: "FiscalCreateRequestBody"
  fiscals-get:
    name: "fiscals-get"
    description: "Get fiscal information"
    handler: src/functions/fiscals/get.handler
    events:
      - httpApi:
          method: get
          path: /v1/fiscals/{id}
          authorizer:
            name: jwtAuthorizer
            type: jwt
  fiscals-list:
    name: "fiscals-get"
    description: "Get fiscals owned by the user"
    handler: src/functions/fiscals/list.handler
    events:
      - httpApi:
          method: get
          path: /v1/fiscals
          authorizer:
            name: jwtAuthorizer
            type: jwt
